import type { NextPage } from "next";
import Head from "next/head";
import HeroSection from "components/Home/HeroSection";
import AboutSection from "components/Home/AboutSection";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Portfolio</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HeroSection />
            <AboutSection />
        </>
    );
};

export default Home;
